name: TipsyTyper
version: 0
author: ItsProtoBish
main: com.proto.TipsyTyper.TipsyTyper
api-version: 1.17
#depend:nodependneeded
starttt:
    description: starts a game
    usage: /<command>
yes:
    description: accepts a game
    usage: /<command>
