name: TipsyTyper
version: 0
author: ItsProtoBish
main: com.proto.TipsyTyper.TipsyTyper
api-version: 1.17
#depend:nodependneeded
commands:
  starttt:
    description: starts the game
    usage: /<starttt>
    aliases: startt